#!/usr/bin/Rscript

require(ggplot2)
require(dplyr)
bdsg.prof <- read.delim('expanded_profiling.cleaned.tsv.gz')
summary(bdsg.prof)
wideScreen <- function(howWide=Sys.getenv("COLUMNS")) {
  options(width=as.integer(howWide))
}
wideScreen(140)
bdsg.prof$sglib.model <- factor(bdsg.prof$sglib.model,levels(bdsg.prof$sglib.model)[c(4,1:3,5)])

sink("build.mem.lm.txt"); with(bdsg.prof, print(summary(lm(build.mem ~ sglib.model + sglib.model * (graph.node.count + graph.edge.count + graph.path.count + graph.step.count + graph.avg.path.depth + graph.seq.length + graph.max.degree + graph.avg.degree + graph.cyclic + graph.avg.edge.delta + graph.feedback.fraction + graph.feedback.arc.count))))); sink()
sink("build.mem.no_og.lm.txt"); with(subset(bdsg.prof, sglib.model != "og"), print(summary(lm(build.mem ~ sglib.model + sglib.model * (graph.node.count + graph.edge.count + graph.path.count + graph.step.count + graph.avg.path.depth + graph.seq.length + graph.max.degree + graph.avg.degree + graph.cyclic + graph.avg.edge.delta + graph.feedback.fraction + graph.feedback.arc.count))))); sink()
sink("build.mem.no_xg.lm.txt"); with(subset(bdsg.prof, sglib.model != "xg"), print(summary(lm(build.mem ~ sglib.model + sglib.model * (graph.node.count + graph.edge.count + graph.path.count + graph.step.count + graph.avg.path.depth + graph.seq.length + graph.max.degree + graph.avg.degree + graph.cyclic + graph.avg.edge.delta + graph.feedback.fraction + graph.feedback.arc.count))))); sink()
sink("build.mem.no_og_xg.lm.txt"); with(subset(bdsg.prof, sglib.model != "xg" & sglib.model != "og"), print(summary(lm(build.mem ~ sglib.model + sglib.model * (graph.node.count + graph.edge.count + graph.path.count + graph.step.count + graph.avg.path.depth + graph.seq.length + graph.max.degree + graph.avg.degree + graph.cyclic + graph.avg.edge.delta + graph.feedback.fraction + graph.feedback.arc.count))))); sink()

#with(bdsg.prof, summary(lm(edge.traversal.time/graph.edge.count ~ sglib.model + sglib.model * (graph.node.count + graph.edge.count + graph.path.count + graph.step.count + graph.avg.path.depth + graph.seq.length + graph.max.degree + graph.avg.degree + graph.cyclic + graph.avg.edge.delta + graph.feedback.fraction + graph.feedback.arc.count))))
sink("edge.traversal.time.lm.txt"); with(bdsg.prof, print(summary(lm(edge.traversal.time ~ sglib.model + sglib.model * (graph.node.count + graph.edge.count + graph.path.count + graph.step.count + graph.avg.path.depth + graph.seq.length + graph.max.degree + graph.avg.degree + graph.cyclic + graph.avg.edge.delta + graph.feedback.fraction + graph.feedback.arc.count))))); sink()
sink("edge.traversal.time_by_edge.count.lm.txt"); with(bdsg.prof, print(summary(lm(edge.traversal.time/graph.edge.count ~ sglib.model + sglib.model * (graph.node.count + graph.edge.count + graph.path.count + graph.step.count + graph.avg.path.depth + graph.seq.length + graph.max.degree + graph.avg.degree + graph.cyclic + graph.avg.edge.delta + graph.feedback.fraction + graph.feedback.arc.count))))); sink()
sink("path.traversal.time_by_step.count_subset_with_paths.lm.txt"); with(subset(bdsg.prof, graph.step.count > 0), print(summary(lm(path.traversal.time/graph.step.count ~ sglib.model + sglib.model * (graph.node.count + graph.edge.count + graph.path.count + graph.step.count + graph.avg.path.depth + graph.seq.length + graph.max.degree + graph.avg.degree + graph.cyclic + graph.avg.edge.delta + graph.feedback.fraction + graph.feedback.arc.count))))); sink()
sink("graph.node.count_by_handle.enumeration.time.lm.txt"); with(bdsg.prof, summary(lm(graph.node.count/handle.enumeration.time ~ sglib.model + sglib.model * (graph.node.count + graph.edge.count + graph.path.count + graph.step.count + graph.avg.path.depth + graph.seq.length + graph.max.degree + graph.avg.degree + graph.cyclic + graph.avg.edge.delta + graph.feedback.fraction + graph.feedback.arc.count)))); sink()
sink("step.count_by_path.traversal.time_subset_with_paths.lm.txt"); with(subset(bdsg.prof, graph.step.count > 0), print(summary(lm(graph.step.count/path.traversal.time ~ sglib.model + sglib.model * (graph.node.count + graph.edge.count + graph.path.count + graph.step.count + graph.avg.path.depth + graph.seq.length + graph.max.degree + graph.avg.degree + graph.cyclic + graph.avg.edge.delta + graph.feedback.fraction + graph.feedback.arc.count))))); sink()
#ggplot(bdsg.prof, aes(x=graph.seq.length, y=graph.node.count/handle.enumeration.time, color=sglib.model)) + geom_point() + scale_x_log10()
#ggsave("bdsg.prof_steps.per.second_vs_seq.length.pdf", width=9.3, height=4.71)
ggplot(bdsg.prof, aes(x=graph.seq.length, y=graph.node.count/handle.enumeration.time, color=sglib.model)) + geom_point() + scale_x_log10() + scale_y_log10()
ggsave("bdsg.prof_handles.per.second_vs_seq.length_logXY.pdf", width=9.3, height=4.71)
ggplot(bdsg.prof, aes(x=graph.seq.length, y=graph.edge.count/edge.traversal.time, color=sglib.model)) + geom_point() + scale_x_log10() + scale_y_log10()
ggsave("bdsg.prof_edges.per.second_vs_seq.length_logXY.pdf", width=9.3, height=4.71)
ggplot(bdsg.prof, aes(x=graph.seq.length, y=graph.step.count/path.traversal.time, color=sglib.model)) + geom_point() + scale_x_log10() + scale_y_log10()
ggsave("bdsg.prof_steps.per.second_vs_seq.length_logXY.pdf", width=9.3, height=4.71) 
ggplot(bdsg.prof, aes(x=graph.seq.length, y=load.mem, color=sglib.model)) + geom_point() + scale_x_log10() + scale_y_log10()
ggsave("bdsg.prof_load.mem_vs_seq.length_logXY.pdf", width=9.3, height=4.71)
#ggplot(bdsg.prof, aes(x=graph.seq.length, y=load.mem/graph.seq.length, color=sglib.model)) + geom_point() + scale_x_log10() + scale_y_log10()
#ggsave("bdsg.prof_load.mem_per_bp_vs_seq.length_logXY.pdf", width=9.3, height=4.71)
#ggplot(bdsg.prof, aes(x=graph.seq.length, y=build.mem/graph.seq.length, color=sglib.model)) + geom_point() + scale_x_log10() + scale_y_log10()
#ggsave("bdsg.prof_build.mem_per_bp_vs_seq.length_logXY.pdf", width=9.3, height=4.71)
ggplot(bdsg.prof, aes(x=graph.seq.length, y=build.mem, color=sglib.model)) + geom_point() + scale_x_log10() + scale_y_log10()
ggsave("bdsg.prof_build.mem_vs_seq.length_logXY.pdf", width=9.3, height=4.71)
ggplot(bdsg.prof, aes(x=graph.seq.length, y=build.time, color=sglib.model)) + geom_point() + scale_x_log10() + scale_y_log10()
ggsave("bdsg.prof_build.time_vs_seq.length_logXY.pdf", width=9.3, height=4.71)
ggplot(bdsg.prof, aes(x=graph.seq.length, y=load.time, color=sglib.model)) + geom_point() + scale_x_log10() + scale_y_log10()
ggsave("bdsg.prof_load.time_vs_seq.length_logXY.pdf", width=9.3, height=4.71)
ggplot(bdsg.prof, aes(x=graph.seq.length, y=graph.seq.length/load.time, color=sglib.model)) + geom_point() + scale_x_log10() + scale_y_log10()
ggsave("bdsg.prof_load.bp_per_second_vs_seq.length_logXY.pdf", width=9.3, height=4.71)
ggplot(bdsg.prof, aes(x=build.time, y=load.time, color=sglib.model, size=graph.seq.length)) + geom_point() + scale_x_log10() + scale_y_log10()
ggsave("bdsg.prof_load_time_vs_build_time_size=seq.length_logXY.pdf", width=9.3, height=4.71)
ggplot(bdsg.prof, aes(x=build.time, y=load.time, color=sglib.model, size=graph.avg.path.depth)) + geom_point() + scale_x_log10() + scale_y_log10()
ggsave("bdsg.prof_load_time_vs_build_time_size=avg.path.depth_logXY.pdf", width=9.3, height=4.71)
